title: Adrian Oboroc's personal site
#email: your-email@example.com
author:      Adrian Oboroc
description: "Blog, links to my projects and some details about me"
baseurl:     ""
url:         "http://www.oboroc.com"
twitter_username: oboroc416
github_username:  oboroc

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
